openapi: 3.0.1
info:
  title: SFTestAPI
  description: API Definition of SFTestAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/sftest
paths:
  /:
    get:
      responses:
        default:
          description: Default response
